// Configuration AutoGenerated by CloudQuery CLI
cloudquery {
  plugin_directory = "./cq/providers"
  policy_directory = "./cq/policies"

  provider "gcp" {
    version = "latest"
  }

  connection {
    // dsn = "tsdb://postgres:pass@localhost:5432/krishancy_api_development?sslmode=disable"
    dsn = "${DSN}"
  }

  history {
    // Save data retention for 7 days
    retention = 7
    // Truncate our fetch by 6 hours per fetch
    truncation = 6
    // Tell Timescale to split our chunks in a daily interval (24 hours)
    interval = 1
  }
}

// Provider Configurations

provider "gcp" {
  configuration {
    // Optional. Filter as described https://cloud.google.com/sdk/gcloud/reference/projects/list --filter
    // project_filter = ""
    // Optional. If not specified either using all projects accessible.
    // project_ids = [<CHANGE_THIS_TO_YOUR_PROJECT_ID>]
    // Optional. ServiceAccountKeyJSON passed as value instead of a file path, can be passed also via env: CQ_SERVICE_ACCOUNT_KEY_JSON
    // service_account_key_json = <YOUR_JSON_SERVICE_ACCOUNT_KEY_DATA>
  }

  // list of resources to fetch
  resources = ["*"]
}
