// Configuration AutoGenerated by CloudQuery CLI
cloudquery {
  plugin_directory = "./cq/providers"
  policy_directory = "./cq/policies"

  provider "okta" {
    version = "latest"
  }

  connection {
    dsn = "tsdb://postgres:pass@localhost:5432/krishancy_api_development?sslmode=disable"
  }

  history {
    // Save data retention for 7 days
    retention = 7
    // Truncate our fetch by 6 hours per fetch
    truncation = 6
    // Tell Timescale to split our chunks in a daily interval (24 hours)
    interval = 1
  }
}

// Provider Configurations

provider "okta" {
  configuration {
    // Optional. Okta Token to access API, you can set this with OKTA_API_TOKEN env variable
    // token = <YOUR_OKTA_TOKEN>
    // Required. You okta domain name. Accessible at `export CQ_VAR_OKTA_DOMAIN="domain"`
    domain = "${OKTA_DOMAIN}"
  }

  // list of resources to fetch
  resources = ["*"]
  // enables partial fetching, allowing for any failures to not stop full resource pull
  enable_partial_fetch = true
}
